include = ["**/Cargo.toml", ".rustfmt.toml", ".taplo.toml", "Cargo.toml", "deny.toml"]

[formatting]
align_entries    = true
column_width     = 120
indent_string    = "\t"
reorder_arrays   = true
reorder_keys     = true
trailing_newline = true

[[rule]]
keys = ["package"]

[rule.formatting]
reorder_keys = false
