[licenses]
allow = [
	"Apache-2.0 WITH LLVM-exception",
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"MIT",
	"MPL-2.0",
	"Unicode-DFS-2016",
	"Zlib",
]
copyleft = "allow"
unlicensed = "deny"
unused-allowed-license = "allow"

[[licenses.clarify]]
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name          = "ring"

[bans]
multiple-versions = "deny"
skip              = []
wildcards         = "deny"

[advisories]
ignore        = []
unmaintained  = "deny"
unsound       = "deny"
vulnerability = "deny"
yanked        = "deny"
